spring:
  profiles:
    active: test
  config:
    import:
      - common/application-dobugs.yml
      - common/application-logging.yml
      - yologa-security/application-jwt.yml
      - yologa-security/application-slack.yml
server:
  tomcat:
    threads:
      max: 10
