spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yologa
    password: yologa
    url: jdbc:mysql://localhost:3306/yologa?characterEncoding=UTF-8
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
