name: YOLOGA CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Execute deploy.sh
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.GCP_ACCOUNT_GMAIL_ID }}
          host: ${{ secrets.GCP_HOST }}
          port: ${{ secrets.GCP_SSH_PORT }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.GCP_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            rm -rf yologa-api
            git clone -b develop https://github.com/dobugs/yologa-api.git
            mv ./yologa-api/scripts/deploy.sh ./deploy.sh
            sh deploy.sh
